///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsInterRegular = 'assets/fonts/Inter-Regular.otf';
  static const String iconsArrowDown = 'assets/icons/arrow-down.svg';
  static const String iconsArrowIosForwardFill =
      'assets/icons/arrow-ios-forward-fill.svg';
  static const String iconsArrowLeftL = 'assets/icons/arrow-left-l.svg';
  static const String iconsCartDuoline = 'assets/icons/cart_duoline.svg';
  static const String iconsHeart = 'assets/icons/heart.svg';
  static const String iconsShareOutline = 'assets/icons/share-outline.svg';
  static const String lottieNoData = 'assets/lottie/No-Data.json';
  static const String translationsArEG = 'assets/translations/ar-EG.json';
  static const String translationsEnUS = 'assets/translations/en-US.json';
}
